/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Products;

/**
 *
 * @author Maaz
 */
public class TopReportF extends javax.swing.JFrame {

    /**
     * Creates new form TopReportF
     */
    public TopReportF() {
        this.setUndecorated(true);
        initComponents();
    }
    
    String user,pass;
    public TopReportF(String user, String pass) {
        this.setUndecorated(true);
        initComponents();
        this.user=user;
        this.pass=pass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profitglass = new javax.swing.JTextField();
        topcustomer = new javax.swing.JTextField();
        profitcustomer = new javax.swing.JTextField();
        topglass = new javax.swing.JTextField();
        topcustomerbtn = new javax.swing.JButton();
        mprofitglass = new javax.swing.JButton();
        mprofitcustomer = new javax.swing.JButton();
        topglassbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mprofitglass1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        topvendor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Most Profitable Glass");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 280, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Top Customer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 210, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOP PRODUCTS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 40, 390, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Most Profitable Customer");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 350, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Top Glass");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 140, 90, 30);

        profitglass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profitglass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        profitglass.setEnabled(false);
        profitglass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitglassActionPerformed(evt);
            }
        });
        getContentPane().add(profitglass);
        profitglass.setBounds(250, 280, 150, 30);

        topcustomer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topcustomer.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        topcustomer.setEnabled(false);
        getContentPane().add(topcustomer);
        topcustomer.setBounds(250, 210, 150, 30);

        profitcustomer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profitcustomer.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        profitcustomer.setEnabled(false);
        getContentPane().add(profitcustomer);
        profitcustomer.setBounds(250, 350, 150, 30);

        topglass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topglass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topglass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        topglass.setEnabled(false);
        topglass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topglassActionPerformed(evt);
            }
        });
        getContentPane().add(topglass);
        topglass.setBounds(250, 140, 150, 30);

        topcustomerbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topcustomerbtn.setText("Get Top Customer");
        topcustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topcustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(topcustomerbtn);
        topcustomerbtn.setBounds(450, 210, 210, 30);

        mprofitglass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mprofitglass.setText("Most Profitable Glass");
        mprofitglass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprofitglassActionPerformed(evt);
            }
        });
        getContentPane().add(mprofitglass);
        mprofitglass.setBounds(450, 280, 220, 30);

        mprofitcustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mprofitcustomer.setText("Most Profitable Customer");
        mprofitcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprofitcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(mprofitcustomer);
        mprofitcustomer.setBounds(450, 350, 220, 30);

        topglassbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topglassbtn.setText("Get Top Glass");
        topglassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topglassbtnActionPerformed(evt);
            }
        });
        getContentPane().add(topglassbtn);
        topglassbtn.setBounds(450, 140, 210, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/iconfinder_back_1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 50, 60, 40);

        mprofitglass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mprofitglass1.setText("Get Top Vendor");
        mprofitglass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprofitglass1ActionPerformed(evt);
            }
        });
        getContentPane().add(mprofitglass1);
        mprofitglass1.setBounds(450, 410, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Top Vendor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 410, 170, 30);

        topvendor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topvendor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        topvendor.setEnabled(false);
        topvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topvendorActionPerformed(evt);
            }
        });
        getContentPane().add(topvendor);
        topvendor.setBounds(250, 410, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/123.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 510);

        setSize(new java.awt.Dimension(925, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profitglassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitglassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitglassActionPerformed

    private void topglassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topglassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topglassActionPerformed

    private void topcustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topcustomerbtnActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        p.setMyUser(user);
        p.setMyPass(pass);
        p.TopCustomer(topcustomer);
    }//GEN-LAST:event_topcustomerbtnActionPerformed

    private void mprofitglassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprofitglassActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        p.setMyUser(user);
        p.setMyPass(pass);
        p.MostProfitableGlass(profitglass, "01-Dec-2018", "31-Dec-2018");
    }//GEN-LAST:event_mprofitglassActionPerformed

    private void mprofitcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprofitcustomerActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        p.setMyUser(user);
        p.setMyPass(pass);
        p.MostProfitableCustomer(profitcustomer);
    }//GEN-LAST:event_mprofitcustomerActionPerformed

    private void topglassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topglassbtnActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        p.setMyUser(user);
        p.setMyPass(pass);
        p.TopGlass(topglass);
    }//GEN-LAST:event_topglassbtnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new AdminPaneldba(user, pass).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void mprofitglass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprofitglass1ActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        p.setMyUser(user);
        p.setMyPass(pass);
        p.TopVendor(topvendor);
    }//GEN-LAST:event_mprofitglass1ActionPerformed

    private void topvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topvendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topvendorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopReportF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopReportF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopReportF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopReportF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopReportF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton mprofitcustomer;
    private javax.swing.JButton mprofitglass;
    private javax.swing.JButton mprofitglass1;
    private javax.swing.JTextField profitcustomer;
    private javax.swing.JTextField profitglass;
    private javax.swing.JTextField topcustomer;
    private javax.swing.JButton topcustomerbtn;
    private javax.swing.JTextField topglass;
    private javax.swing.JButton topglassbtn;
    private javax.swing.JTextField topvendor;
    // End of variables declaration//GEN-END:variables
}
