/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.User;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class UserCreateForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public UserCreateForm() {
        this.setUndecorated(true);
        initComponents();
    }
    
    String user,pass;
    public UserCreateForm(String user, String pass){
        this.setUndecorated(true);
        initComponents();
        this.user = user;
        this.pass = pass;
        System.out.println(user+pass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        CityComboBox = new javax.swing.JComboBox<>();
        CNICTextField = new javax.swing.JFormattedTextField();
        ContactTextField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/minimalism-1513898226715-9320.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 150, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 190, 110, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CNIC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 240, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 290, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 340, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 380, 110, 50);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setEnabled(false);
        jTextField1.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 150, 220, 34);

        NameTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameTextField);
        NameTextField.setBounds(370, 200, 220, 28);

        CityComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karachi", "Lahore", "Islamabad" }));
        CityComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(CityComboBox);
        CityComboBox.setBounds(370, 340, 220, 30);

        try {
            CNICTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CNICTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CNICTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(CNICTextField);
        CNICTextField.setBounds(370, 240, 220, 30);

        try {
            ContactTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ContactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContactTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ContactTextField);
        ContactTextField.setBounds(370, 290, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 40, 333, 63);

        ClearBtn.setBackground(new java.awt.Color(153, 153, 153));
        ClearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/if_edit-clear_118917.png"))); // NOI18N
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBtn);
        ClearBtn.setBounds(370, 460, 60, 40);

        NextBtn.setBackground(new java.awt.Color(153, 153, 153));
        NextBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/if_go-next_118773.png"))); // NOI18N
        NextBtn.setText("Create ID");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NextBtn);
        NextBtn.setBounds(439, 460, 150, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/if_user_173122 (1).png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 0, 130, 140);

        datechooser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datechooser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datechooser);
        datechooser.setBounds(370, 390, 220, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/iconfinder_back_1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 50, 60, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/123.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 840, 540);

        setSize(new java.awt.Dimension(849, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactTextFieldActionPerformed
    
    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        NameTextField.setText("");
        CNICTextField.setText("");
        ContactTextField.setText("");
        CityComboBox.setSelectedItem("");
        datechooser.setDate(null);
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
        String name = NameTextField.getText();
        String CNIC = CNICTextField.getText();
        String contact = ContactTextField.getText();
        String city = String.valueOf(CityComboBox.getSelectedItem());
        
        DateFormat df = new SimpleDateFormat("dd-MMM-yyyy");
        String date = df.format(datechooser.getDate());        
        //System.out.println(date);

        if(!(name.isEmpty()) && !(CNIC.isEmpty()) && !(contact.isEmpty()) && !(date.isEmpty()) 
                && !(city.isEmpty())){

            User u = new User();
            u.setMyUser(user);
            u.setMyPass(pass);
            if(u.UserCreateCheck(name)){
                JOptionPane.showMessageDialog(null, "Please Choose different username");
            }
            else{
                u.setCNIC(CNIC);
                u.setCity(city);
                u.setContactNo(contact);
                u.setName(name);
                u.setDate(date);
                u.InsertUser(u);
                u.provideUserID(name);
                new UserForm(user, pass).setVisible(true);
                //new GlassType(date, WIDTH).setVisible(true);
                dispose();
            }          
        }
        else{
            JOptionPane.showMessageDialog(null, "Fill out all the fields. ");
        }     
    }//GEN-LAST:event_NextBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new UserForm(user, pass).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCreateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CNICTextField;
    private javax.swing.JComboBox<String> CityComboBox;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JFormattedTextField ContactTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton NextBtn;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
